spring:
  application:
      name: BookTask

  datasource:
    url: jdbc:mysql://localhost:3306/booktask?useSSL=false&serverTimezone=UTC
    username: root
    password: qwerty123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:/db/changelog/dbchangelog.yaml
